jo = "0.13"

[module.api]
kind = "lib"
platform = "python"
src = ["../shared/Types.jo", "API.jo"]

[module.runtime]
kind = "lib"
platform = "python"
enable-ffi = true
src = ["../shared/Depot.jo", "Runtime.jo", "PlanImpl.jo"]
depth = 2
modules = ["api"]
packages = [{ name = "harpe", version = "0.9" }]

[module.guest]
kind = "app"
platform = "python"
src = ["Task.jo"]
depth = 2
modules = ["api", { id = "runtime", link = true }]

links = [
  { from = "jo.main", to = "sandbox.runtime.main" },
  { from = "sandbox.api.runTask", to = "sandbox.guest.runTask" },
]
